# Generated by Django 6.1.1 on 2026-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume_builder",
            "0002_alter_generatedresume_id_alter_resumetemplate_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedresume",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="resumeprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="resumetemplate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
