# Generated by Django 6.1.1 on 2026-09-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_alter_generatedresume_id_alter_resumeprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='ats_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='sample_file',
            field=models.FileField(blank=True, upload_to='resume_templates/%Y/%m/'),
        ),
    ]
