# Generated by Django 6.1.1 on 2026-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0008_alter_generatedresume_id_alter_resumeprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='template_data_snapshot',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
