# Generated by Django 6.1.1 on 2026-10-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0009_generatedresume_template_data_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
