# Generated by Django 6.1.1 on 2026-09-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
