# Generated by Django 4.2.30 on 2026-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_follow_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
