from django.utils import timezone
from career.models import (
    CareerAnalysis,
    InterviewResponse,
    InterviewSession,
)
from agents.services.interview_evaluator import (
    evaluate_interview_answer,
)

def build_interview_questions(
    *,
    interview_preparation,
    target_role,
    interview_type="mixed",
):
    """
    Convert the existing interview preparation generated by the
    career analysis into a simulator question set.

    The simulator must stay grounded in the existing career analysis.
    """

    preparation = interview_preparation or {}

    technical_questions = preparation.get(
        "technical_questions",
        [],
    )

    project_questions = preparation.get(
        "project_questions",
        [],
    )

    gap_based_questions = preparation.get(
        "gap_based_questions",
        [],
    )

    behavioral_questions = preparation.get(
        "behavioral_questions",
        [],
    )

    question_pool = []

    if interview_type in ("mixed", "technical"):
        question_pool.extend(technical_questions)

    if interview_type in ("mixed", "project"):
        question_pool.extend(project_questions)

    if interview_type in ("mixed", "gap_based"):
        question_pool.extend(gap_based_questions)

    if interview_type in ("mixed", "behavioral"):
        question_pool.extend(behavioral_questions)

    if not question_pool:
        raise ValueError(
            "No interview questions are available for this career analysis."
        )

    # Keep the simulator deterministic and grounded in the
    # questions already generated by the career analysis.
    normalized_questions = []

    for item in question_pool:
        if isinstance(item, dict):
            question = item.get("question", "").strip()
            category = item.get("category", "").strip()
            difficulty = item.get("difficulty", "").strip()
            reason = item.get("reason", "").strip()
        else:
            question = getattr(item, "question", "").strip()
            category = getattr(item, "category", "").strip()
            difficulty = getattr(item, "difficulty", "").strip()
            reason = getattr(item, "reason", "").strip()

        if not question:
            continue

        normalized_questions.append(
            {
                "question": question,
                "category": category or "general",
                "difficulty": difficulty or "medium",
                "reason": reason,
            }
        )

    if not normalized_questions:
        raise ValueError(
            "The interview preparation contains no valid questions."
        )

    return normalized_questions


def create_interview_session(
    *,
    user,
    career_analysis,
    target_role="",
    interview_type="mixed",
):
    if not isinstance(career_analysis, CareerAnalysis):
        raise ValueError(
            "A valid career analysis is required."
        )

    if career_analysis.user_id != user.id:
        raise ValueError(
            "You do not have access to this career analysis."
        )

    questions = build_interview_questions(
        interview_preparation=career_analysis.interview_preparation,
        target_role=target_role,
        interview_type=interview_type,
    )

    resolved_target_role = (
        target_role.strip()
        if target_role
        else "Career Interview"
    )

    session = InterviewSession.objects.create(
        user=user,
        career_analysis=career_analysis,
        target_role=resolved_target_role,
        interview_type=interview_type,
        questions=questions,
        current_question_index=0,
        completed=False,
        overall_score=None,
    )

    return session

def submit_interview_answer(
    *,
    user,
    session_id,
    answer,
):
    answer = answer.strip()

    if not answer:
        raise ValueError(
            "Interview answer cannot be empty."
        )

    try:
        session = InterviewSession.objects.get(
            id=session_id,
            user=user,
        )
    except InterviewSession.DoesNotExist:
        raise ValueError(
            "Interview session not found."
        )

    if session.completed:
        raise ValueError(
            "This interview session has already been completed."
        )

    questions = session.questions or []

    question_index = session.current_question_index

    if question_index >= len(questions):
        raise ValueError(
            "No more questions are available."
        )

    current_question = questions[question_index]

    question = current_question.get(
        "question",
        "",
    )

    category = current_question.get(
        "category",
        "general",
    )

    difficulty = current_question.get(
        "difficulty",
        "medium",
    )

    career_analysis = session.career_analysis

    if not career_analysis:
        raise ValueError(
            "Career analysis is missing from this interview session."
        )

    evaluation = evaluate_interview_answer(
        question=question,
        category=category,
        difficulty=difficulty,
        user_answer=answer,
        resume_context=career_analysis.resume_context,
        job_requirements=career_analysis.job_requirements,
    )

    evaluation_data = evaluation

    response = InterviewResponse.objects.create(
        session=session,
        question_index=question_index,
        question=question,
        category=category,
        difficulty=difficulty,
        answer=answer,
        evaluation=evaluation_data,
        score=evaluation_data.get("score"),
    )

    next_question_index = question_index + 1

    session.current_question_index = next_question_index

    completed = (
        next_question_index >= len(questions)
    )

    session.completed = completed

    if completed:
        responses = InterviewResponse.objects.filter(
            session=session,
        )

        scores = [
            item.score
            for item in responses
            if item.score is not None
        ]

        if scores:
            session.overall_score = round(
                sum(scores) / len(scores)
            )

        session.completed_at = timezone.now()

    session.save(
        update_fields=[
            "current_question_index",
            "completed",
            "overall_score",
            "completed_at",
        ]
    )

    next_question = None

    if not completed:
        next_question = questions[
            next_question_index
        ]

    return {
        "response_id": response.id,
        "question_index": question_index,
        "evaluation": evaluation_data,
        "completed": completed,
        "overall_score": session.overall_score,
        "next_question_index": (
            next_question_index
            if not completed
            else None
        ),
        "next_question": next_question,
    }