# Generated by Django 6.1.1 on 2026-09-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
