# Generated by Django 6.1.1 on 2026-09-17 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_summary', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('programming_languages', models.JSONField(default=list)),
                ('frameworks', models.JSONField(default=list)),
                ('tools_and_technologies', models.JSONField(default=list)),
                ('ai_ml_technologies', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='resumes.resume')),
            ],
        ),
    ]
