# Generated by Django 6.1.1 on 2026-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_resumeintelligence"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="processing_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resume",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
