# Generated by Django 6.1.1 on 2026-09-30 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobposting'),
        ('resumes', '0009_alter_resume_id_alter_resumeintelligence_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content_type',
            field=models.CharField(default='md', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='interview_prep',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_resumes', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='resume',
            name='original_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='outreach_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='processed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_resumes', to='resumes.resume'),
        ),
        migrations.CreateModel(
            name='ResumePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_hash', models.CharField(max_length=64)),
                ('source_hash', models.CharField(max_length=64)),
                ('job_hash', models.CharField(max_length=64)),
                ('prompt_id', models.CharField(blank=True, default='', max_length=64)),
                ('improvements', models.JSONField(default=list)),
                ('response', models.JSONField(blank=True, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=64)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_previews', to='jobs.jobposting')),
                ('source_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_previews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_resume', 'job', 'expires_at'], name='resumes_res_source__a5eb79_idx')],
            },
        ),
    ]
