# Generated by Django 6.1.1 on 2026-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_resume_content_type_resume_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='builder_content',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
