# Generated by Django 6.1.1 on 2026-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_careeranalysis_resume_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranalysis',
            name='interview_preparation',
            field=models.JSONField(default=dict),
        ),
    ]
