# Generated by Django 6.1.1 on 2026-09-24 14:38

import django.db.models.deletion
from django.db import migrations, models


def backfill_resume_snapshot(apps, schema_editor):
    CareerAnalysis = apps.get_model("career", "CareerAnalysis")

    for analysis in CareerAnalysis.objects.select_related(
        "resume"
    ).iterator():
        if not analysis.resume:
            continue

        if not analysis.resume_title:
            analysis.resume_title = analysis.resume.title

        if not analysis.resume_context:
            analysis.resume_context = (
                analysis.resume.extracted_text or ""
            )

        analysis.save(
            update_fields=[
                "resume_title",
                "resume_context",
            ]
        )


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_careeranalysis_interview_preparation'),
        ('resumes', '0003_resumeintelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranalysis',
            name='resume_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='careeranalysis',
            name='resume_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='careeranalysis',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_analyses', to='resumes.resume'),
        ),
        migrations.RunPython(
            backfill_resume_snapshot,
            reverse_backfill,
        ),
    ]
