# Generated by Django 6.1.1 on 2026-09-25 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0005_careerroadmap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_role",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("interview_type", models.CharField(default="mixed", max_length=50)),
                ("questions", models.JSONField(default=list)),
                ("current_question_index", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("overall_score", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "career_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_sessions",
                        to="career.careeranalysis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_index", models.PositiveIntegerField()),
                ("question", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("difficulty", models.CharField(max_length=50)),
                ("answer", models.TextField()),
                ("evaluation", models.JSONField(default=dict)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="career.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["question_index"],
                "unique_together": {("session", "question_index")},
            },
        ),
    ]
