# Generated by Django 4.2.30 on 2026-10-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_alter_careeranalysis_id_alter_careerroadmap_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerroadmap',
            name='learner_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.CreateModel(
            name='RoadmapLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('skill', 'Skill'), ('topic', 'Topic'), ('project', 'Project'), ('phase', 'Phase')], max_length=20)),
                ('item_index', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, default='')),
                ('estimated_time', models.CharField(blank=True, default='', max_length=60)),
                ('lesson_data', models.JSONField(default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='career.careerroadmap')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('roadmap', 'content_type', 'item_index')},
            },
        ),
    ]
